# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
  boot = {

    initrd.availableKernelModules = [
      "xhci_pci"
      "thunderbolt"
      "vmd"
      "nvme"
      "usb_storage"
      "sd_mod"
      "rtsx_pci_sdmmc"
    ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];

    # Reduce the selection time to 2 seconds.
    # If this gets changed to `0` you can still access the selections by
    # holding space during boot.
    loader.timeout = 2;
    # Each generation costs ~215M of ESP because nixos-facter puts `nvidia` in
    # `initrd.kernelModules` and `nvidia.ko` alone is 85M. GRUB stages every
    # kernel it needs before pruning obsolete ones, so the peak is
    # `configurationLimit + 1` generations -- 4 * 215M ~= 860M of the 5G ESP.
    loader.grub.configurationLimit = 3;
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.facter.reportPath = ./facter.json;
}
