# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
  boot = {

    initrd.availableKernelModules = [
      "xhci_pci"
      "thunderbolt"
      "vmd"
      "nvme"
      "usb_storage"
      "sd_mod"
      "rtsx_pci_sdmmc"
    ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];

    # Reduce the selection time to 2 seconds.
    # If this gets changed to `0` you can still access the selections by
    # holding space during boot.
    loader.timeout = 2;
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # hardware.bluetooth = {
  #   settings = {
  #     General = {
  #       Privacy = "device";
  #       JustWorksRepairing = "always";
  #       Class = "0x000100";
  #     };
  #   };
  # };
  # hardware.bluetooth = {
  #   enable = true;
  #   powerOnBoot = true;
  #   settings = {
  #     General = {
  #       # Shows battery charge of connected devices on supported
  #       # Bluetooth adapters. Defaults to 'false'.
  #       Experimental = true;
  #       # When enabled other devices can connect faster to us, however
  #       # the tradeoff is increased power consumption. Defaults to
  #       # 'false'.
  #       FastConnectable = true;
  #     };
  #     Policy = {
  #       # Enable all controllers when they are found. This includes
  #       # adapters present on start as well as adapters that are plugged
  #       # in later on. Defaults to 'true'.
  #       AutoEnable = true;
  #     };
  #   };
  # };
  # services.blueman.enable = true;
}
